### ISSUE TITLE
no masks and frames around pictures in pdf

### ISSUE THREAD

**Issue by markojerofke** [rbodziony/mcf2pdf#12]
The masks and frames around pictures are lost since CEWE Fotobuch 6.4 versions even if the pictures are taken correct (zoom, position etc.). This was also an issue here: https://github.com/albrechtf/mcf2pdf/issues/7
The same issue?
Thanks, Marko

**Comment by rbodziony** [comment]
Can you show sample screen shot and some part of xml as example ?

**Comment by markojerofke** [comment]
I attach two PDFs created with mcf2pdf-0.3.7-SNAPSHOT version. So the masking is working with CEWE version 6.3.6 but not with version 6.4.1. For the frame I have to correct me, it's working fine as you can see.
The .mcf is attached, created with CEWE 6.3.6.
Thanks, Marko
[masks-CEWE-6.3.6.pdf](https://github.com/rbodziony/mcf2pdf/files/2888415/masks-CEWE-6.3.6.pdf)
[masks-CEWE-6.4.1.pdf](https://github.com/rbodziony/mcf2pdf/files/2888416/masks-CEWE-6.4.1.pdf)
[masks.mcf.txt](https://github.com/rbodziony/mcf2pdf/files/2888419/masks.mcf.txt)

**Comment by rbodziony** [comment]
i will take look on this ! :)

**Comment by rbodziony** [comment]
check this https://github.com/rbodziony/mcf2pdf/releases/tag/3.7.8 if it works

**Comment by markojerofke** [comment]
Now it works, thanks a lot!
