### ISSUE TITLE
mask breaks mcf2pdf

### ISSUE THREAD

**Issue by markojerofke** [rbodziony/mcf2pdf#17]
Using mcf2pdf-0.3.8-SNAPSHOT with specific mask breaks mcf2pdf with error:

[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /Programme/CEWE/Resources/photofun/decorations/Buchstaben.xml
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /Programme/CEWE/Resources/photofun/decorations/Farben.xml
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /Programme/CEWE/Resources/photofun/decorations/cliparts_default.xml
[WARN ] net.sf.mcf2pdf.mcfglobals.McfResourceScanner Failed to load decorations from: /Programme/CEWE/Resources/photofun/decorations/masks_default.xml
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 0+1...
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.NullPointerException
        at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.passePartoutDesignElementId(McfResourceScanner.java:218)
        at net.sf.mcf2pdf.pagebuild.PageRenderContext.getFadingFromDesignedElementID(PageRenderContext.java:232)
        at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:94)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:253)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

I've attached the test-mcf file.
[Test.mcf.txt](https://github.com/rbodziony/mcf2pdf/files/2991444/Test.mcf.txt)

**Comment by rbodziony** [comment]
Tx let me see it can you also enable debug and provide log ?

**Comment by markojerofke** [comment]
I attached the last ones beginning from reading the file. Regards, Marko

[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Reading MCF file
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Preparing temporary working directory
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText processing html<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Courier'; font-size:16pt; font-weight:400; font-style:normal;"><p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText body =<body style=" font-family:'Courier'; font-size:16pt; font-weight:400; font-style:normal;">
 <p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br></p>
</body>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText p =<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br></p>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText p.tagname =p
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText para =net.sf.mcf2pdf.pagebuild.FormattedTextParagraph@5f7cc6fd
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText processing html<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'Courier'; font-size:12pt; font-weight:400; font-style:normal;"><p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText body =<body style=" font-family:'Courier'; font-size:12pt; font-weight:400; font-style:normal;">
 <p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br></p>
</body>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText p =<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br></p>
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText p.tagname =p
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText para =net.sf.mcf2pdf.pagebuild.FormattedTextParagraph@3fcc58f8
[DEBUG] net.sf.mcf2pdf.pagebuild.BitmapPageBuilder Creating full page image from page elements
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText Rendering text
[DEBUG] net.sf.mcf2pdf.pagebuild.PageText Rendering text
[DEBUG] net.sf.mcf2pdf.Mcf2FoConverter Starting rendering of 32 pages
[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering pages 0+1...
[DEBUG] net.sf.mcf2pdf.pagebuild.BitmapPageBuilder Creating full page image from page elements
[DEBUG] net.sf.mcf2pdf.pagebuild.PageImage Rendering image /ComputerMarko/Bilder/Fotobestellungen/Test_mcf-Dateien/2018-12-14_18-13-331.jpeg
[DEBUG] net.sf.mcf2pdf.pagebuild.PageImage grabbing fadding from image
[DEBUG] net.sf.mcf2pdf.pagebuild.PageImage grabing fadding from PassePartout=99012
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.NullPointerException
        at net.sf.mcf2pdf.mcfglobals.McfResourceScanner.passePartoutDesignElementId(McfResourceScanner.java:218)
        at net.sf.mcf2pdf.pagebuild.PageRenderContext.getFadingFromDesignedElementID(PageRenderContext.java:232)
        at net.sf.mcf2pdf.pagebuild.PageImage.renderAsBitmap(PageImage.java:94)
        at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
        at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:253)
        at net.sf.mcf2pdf.Main.main(Main.java:202)

**Comment by rbodziony** [comment]
Can you put all debug here ? Not part

**Comment by markojerofke** [comment]
Sorry, lot of output....
[Test_Output.txt](https://github.com/rbodziony/mcf2pdf/files/3000830/Test_Output.txt)

**Comment by rbodziony** [comment]
ok looks like he cant find mask so let me create some sample with this mask to find root cause of this issue it will take some time

**Comment by rbodziony** [comment]
@markjorekfe
using default CEWE install at ubuntu i was able to create pdf
the mask which is missing is installed here /home/<..username....>/CEWE/Mein CEWE FOTOBUCH/Resources/photofun/decorations/7310-MASK-CC.clp
looking at your debug didnt see this in 
/ComputerMarko/Programme/CEWE/Resources/photofun/decorations/....
 Regards

**Comment by markojerofke** [comment]
Yes, you are completely right. By mistake I pointed the MCF_INSTALL_DIR to a 6.3 version of CEWE where this mask is not included. Sorry for the inconvenience, it's working fine pointing to the correct CEWE version in the mcf2pdf file.
Regards, Marko
