### ISSUE TITLE
Update for 6.4.3

### ISSUE THREAD

**Issue by ipoua** [rbodziony/mcf2pdf#18]
Hi rbodziony! mcf2pdf doesn't work with the newest Cewe 6.4.3 update.

[INFO ] net.sf.mcf2pdf.Mcf2FoConverter Rendering cover...
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: koordinaten_weiss_cover_back_landscape
[WARN ] net.sf.mcf2pdf.pagebuild.PageBackground Background not found for page 0: kraeftige_farben_cover_front_landscape
[WARN ] net.sf.mcf2pdf.pagebuild.PageClipart Clipart not found: null
[ERROR] net.sf.mcf2pdf.Main An exception has occured
java.lang.IllegalArgumentException: Width (0) and height (0) cannot be <= 0
	at java.desktop/java.awt.image.DirectColorModel.createCompatibleWritableRaster(DirectColorModel.java:1016)
	at java.desktop/java.awt.image.BufferedImage.<init>(BufferedImage.java:333)
	at net.sf.mcf2pdf.mcfelements.util.ImageUtil.loadClpFile(ImageUtil.java:166)
	at net.sf.mcf2pdf.pagebuild.PageClipart.renderAsBitmap(PageClipart.java:66)
	at net.sf.mcf2pdf.pagebuild.BitmapPageBuilder.addToDocumentBuilder(BitmapPageBuilder.java:75)
	at net.sf.mcf2pdf.Mcf2FoConverter.convert(Mcf2FoConverter.java:224)
	at net.sf.mcf2pdf.Main.main(Main.java:202)

**Comment by rbodziony** [comment]
Can you paste sample 1-2 page XML from 6.4.3?

**Comment by ipoua** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<fotobook art_id="9759" externalProjectId="" identifier="a18ee3a3-8ae4-4561-b56c-4004e31d8bbc" imagedir="test.mc_mcf-Dateien" isDataMcf="0" productname="ALB35" startdatecalendarium="" useSpineLogo="1" version="4.0">
    <project createdWithHPSVersion="6.4.3" createdWithHPSVersionBuild="20190416" projectID="4de4f323-75a0-4f9a-abf9-6a91ebcaf08c" projectIDCreatedEpoch="1559152832"/>
    <savingVersion compatibilityVersion="6.4.2" programversion="6.4.3" programversionBuild="20190416" savetime="2019-05-29 20:00"/>
    <articleConfig normalpages="30" pagenaming="1" productvariant="pages:30" totalpages="35"/>
    <pagenumbering bgcolor="#00000000" fontbold="0" fontfamily="helvetica" fontitalics="0" fontsize="24" format="0" margin="111" position="0" textcolor="#ff000000" textstring="%" verticalMargin="50">
        <outline enabled="0" width="1"/>
    </pagenumbering>
    <extra>
        <lastTextFormat Alignment="ALIGNLEFT" IndentMargin="5" VerticalIndentMargin="0" backgroundColor="#fffff6b5" font="Bluff,36,-1,5,50,0,0,0,0,0" foregroundColor="#ff000000" hasOutline="0"/>
    </extra>
    <page designStyleID="-1" pagenr="0" rotation="0" type="fullcover">
        <bundlesize height="2100" width="5575"/>
        <designElementIDs background="201" layout="82068"/>
        <background alignment="4" designElementId="201" rotation="0" type="1"/>
        <background designElementId="82068" layout="1" templatename="fullcoverpage_landscape,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="2300" left="-100" rotation="0" top="-100" width="2845" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="2300" left="2830" rotation="0" top="-100" width="2845" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="spinelogoarea" isResizable="0">
            <position height="42,5" left="2730,9" rotation="270" top="1972,65" width="112,2" zposition="6999"/>
            <decoration/>
            <clipart designElementId="0"/>
        </area>
        <area areatype="textarea" isResizable="1">
            <position height="550" left="3030,36496350365" rotation="0" top="200" width="2344,270072992701" zposition="7000"/>
            <decoration/>
            <text applySpotColor="0" areaTextType="title"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'helvetica'; font-size:12pt; font-weight:400; font-style:normal;">
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>]]><outline enabled="0" width="1"/>
                <textFormat Alignment="ALIGNLEFT" IndentMargin="0" VerticalIndentMargin="50" backgroundColor="#00000000" font="helvetica,12,-1,5,50,0,0,0,0,0" foregroundColor="#ff000000" hasOutline="0"/>
            </text>
        </area>
        <area areatype="spinetextarea" isResizable="0">
            <position height="85" left="2012,5" rotation="270" top="782,5" width="1550" zposition="7000"/>
            <decoration/>
            <text applySpotColor="0" areaTextType="spine"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta name="qrichtext" content="1" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body style=" font-family:'helvetica'; font-size:12pt; font-weight:400; font-style:normal;">
<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>]]><outline enabled="0" width="0"/>
                <textFormat Alignment="ALIGNLEFT" IndentMargin="0" VerticalIndentMargin="0" backgroundColor="#00000000" font="helvetica,12,-1,5,50,0,0,0,0,0" foregroundColor="#ff000000" hasOutline="0"/>
            </text>
        </area>
    </page>
    <page designStyleID="-1" pagenr="0" rotation="0" type="spine">
        <bundlesize height="2100" width="5575"/>
        <designElementIDs background="201"/>
        <background alignment="4" designElementId="201" rotation="0" type="1"/>
    </page>
    <page designStyleID="-1" pagenr="0" rotation="0" type="fullcover">
        <bundlesize height="2100" width="5575"/>
        <designElementIDs background="201" layout="82074"/>
        <background alignment="4" designElementId="201" rotation="0" type="1"/>
        <background designElementId="82074" layout="1" templatename="fullcoverpage_with_text_landscape,normal"/>
    </page>
    <page designStyleID="-1" pagenr="0" rotation="0" type="emptypage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="1" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="2" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125025"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125025" layout="1" templatename="XXL-2 Bilder quer 1_x,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <designElementIDs passepartout="46524"/>
            <decoration/>
            <image filename="safecontainer:/DSCI3067.jpeg" passepartoutDesignElementId="46524" useABK="1">
                <cutout left="-620" scale="0.473602" top="0"/>
            </image>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <designElementIDs passepartout="46524"/>
            <decoration/>
            <image filename="safecontainer:/DSCI3068.jpeg" passepartoutDesignElementId="46524" useABK="1">
                <cutout left="-620" scale="0.473602" top="0"/>
            </image>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1066" left="1270" rotation="0" top="873,9999999999998" width="1180" zposition="104"/>
            <designElementIDs passepartout="46524"/>
            <decoration/>
            <image filename="safecontainer:/evdf8b97_1_DSCI3062.jpeg" passepartoutDesignElementId="46524" useABK="1">
                <cutout left="0" scale="0.305383" top="-253.667"/>
            </image>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1066" left="250" rotation="0" top="110,0000000000001" width="1180" zposition="105"/>
            <designElementIDs passepartout="46524"/>
            <decoration/>
            <image filename="safecontainer:/cw11tnqo_1_DSCI3066.jpeg" passepartoutDesignElementId="46524" useABK="1">
                <cutout left="0" scale="0.305383" top="-253.667"/>
            </image>
        </area>
        <area areatype="textarea" backgroundcolor="4294964917" isResizable="1">
            <position height="534,1989334569905" left="263,3897519128217" rotation="0" top="1346,626478089497" width="864,363552051936" zposition="7000"/>
            <decoration/>
            <text applySpotColor="0" areaTextType="content"><![CDATA[<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd"><html><head><meta name="qrichtext" content="1" /><style type="text/css">p, li { white-space: pre-wrap; }</style></head><body style=" font-family:'helvetica'; font-size:16pt; font-weight:400; font-style:normal;"><table style="-qt-table-type: root; margin-top:5px; margin-bottom:5px; margin-left:5px; margin-right:5px;"><tr><td style="border: none;"><p style=" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><span style=" font-family:'Bluff'; font-size:36pt; color:#000000;">Test text</span></p></td></tr></table></body></html>]]><outline color="#ff000000" enabled="0" width="1"/>
                <textFormat Alignment="ALIGNLEFT" IndentMargin="5" VerticalIndentMargin="50" backgroundColor="#fffff6b5" font="helvetica,16,-1,5,50,0,0,0,0,0" foregroundColor="#ff000000" hasOutline="0"/>
            </text>
        </area>
    </page>
    <page designStyleID="-1" pagenr="3" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="4" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="5" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="6" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="7" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="8" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="9" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="10" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="11" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="12" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="13" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="14" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="15" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="16" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="17" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="18" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="19" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="20" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="21" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="22" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="23" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="24" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="25" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="26" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="27" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="28" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="2810" rotation="0" top="110" width="1200" zposition="101"/>
            <decoration/>
            <image/>
        </area>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="4090" rotation="0" top="110" width="1200" zposition="102"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="29" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_005,normal"/>
    </page>
    <page designStyleID="-1" pagenr="30" rotation="0" type="normalpage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201" layout="125026"/>
        <background alignment="1" designElementId="201" rotation="0" type="1"/>
        <background designElementId="125026" layout="1" templatename="schema_landscape_001,normal"/>
        <area areatype="imagearea" isResizable="1">
            <position height="1830" left="110" rotation="0" top="110" width="2480" zposition="100"/>
            <decoration/>
            <image/>
        </area>
    </page>
    <page designStyleID="-1" pagenr="0" rotation="0" type="emptypage">
        <bundlesize height="2050" width="5400"/>
        <designElementIDs background="201"/>
        <background alignment="3" designElementId="201" rotation="0" type="1"/>
    </page>
    <userfeedback></userfeedback>
    <fotoRelationships>
        <foto id="file:///home/patrick/Bilder/Budapest 2019/DSCI3062.JPG">
            <foto id="safecontainer:/DSCI3062.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY">
                <foto id="safecontainer:/evdf8b97_1_DSCI3062.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
            </foto>
        </foto>
        <foto id="file:///home/patrick/Bilder/Budapest 2019/DSCI3068.JPG">
            <foto id="safecontainer:/DSCI3068.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY"/>
        </foto>
        <foto id="file:///home/patrick/Bilder/Budapest 2019/DSCI3067.JPG">
            <foto id="safecontainer:/DSCI3067.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY"/>
        </foto>
        <foto id="file:///home/patrick/Bilder/Budapest 2019/DSCI3066.JPG">
            <foto id="safecontainer:/DSCI3066.jpeg" nature="RELATIONSHIP_ONE_TO_ONE_COPY">
                <foto id="safecontainer:/cw11tnqo_1_DSCI3066.jpeg" nature="RELATIONSHIP_MODIFIED_COPY"/>
            </foto>
        </foto>
    </fotoRelationships>
    <statistics assistantUsed="0" countPauses="0" elapsedTimeGross="2019-05-29T19:57:23" elapsedTimeNet="189" fotosAdded="7" fotosRemoved="3" pauseTime="0" sessionsUsed="1"/>
</fotobook>

**Comment by ipoua** [comment]
[test.txt](https://github.com/rbodziony/mcf2pdf/files/3236186/test.txt)

**Comment by rbodziony** [comment]
Tx I will take look at this issue

**Comment by rbodziony** [comment]
Also can you run in debug mode and provide output log?

**Comment by ipoua** [comment]
[debug_output.txt](https://github.com/rbodziony/mcf2pdf/files/3242833/debug_output.txt)

I'm not sure if that is what you want.
Thank you for your efforts!

**Comment by rbodziony** [comment]
I mean using -d option and then capture output and provide to me tx

**Comment by ipoua** [comment]
[ouput.txt](https://github.com/rbodziony/mcf2pdf/files/3270992/ouput.txt)

Sorry for my late reply, here is the output.

**Comment by rbodziony** [comment]
Yes this is a problem with 6.4.3 need not possible currently use 6.4.3 as they change mcf format so need create new version it will take me some time 🗡

**Comment by kovilaji** [comment]
Hello!

Please update the program for compatibile to the latest Cewe version.
Or write a link to the Cewe 6.4.3 version.

Thanks!

**Comment by rbodziony** [comment]
Last version 0.7.1 should work with this

**Comment by rbodziony** [comment]
Check this -> https://github.com/rbodziony/mcf2pdf/releases/tag/0.7.1.beta.1
