### ISSUE TITLE
"Easte egg" issue at beginning on the first content page

### ISSUE THREAD

**Issue by martind1983** [rbodziony/mcf2pdf#9]
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Win 10
Cewe Fotobuch
mcf2pdf 0.3.5

"easter egg" issue at the beginning of the foto book (first content page):

design:
![design_blackbackground](https://user-images.githubusercontent.com/41088233/43039371-18df31a6-8d2c-11e8-88cd-bcc1c99781dd.PNG)
output in PDF:
![output_image](https://user-images.githubusercontent.com/41088233/43039372-1e0cfe7e-8d2c-11e8-93cc-80dcd36d10b2.PNG)

Debug: 
[debug_clipart.txt](https://github.com/rbodziony/mcf2pdf/files/2216427/debug_clipart.txt)

Fotobuch first 4 pages
[Fotobuch_FirstPages.zip](https://github.com/rbodziony/mcf2pdf/files/2216432/Fotobuch_FirstPages.zip)

**Comment by rbodziony** [comment]
ok 
this "egg" is hidden in CEWE but in xml(.mcf) 
do backup this file and then remove ...
 <area height="636" areatype="clipartarea" isResizable="1" zposition="105" alpha="1" top="698" width="699.2334494773519" rotation="0" left="840.8885017421602">
   <designElementIDs clipart="30074"/>
   <border position="outside" enabled="1" width="2" color="#ff000000" applySpotColor="0"/>
   <clipart uniqueName="clipart_art_6520075_X_1.svg">
    <ClipartConfiguration applySpotColor="1"/>
   </clipart>
  </area>
...
i guess it after conversion something goes wrong

**Comment by martind1983** [comment]
True - thanks for this one :-) solved !
